import Head from 'next/head';
import { NextPage } from 'next';
import Card from '../components/Card';
import Footer from '../components/Footer';


const Home : NextPage =()=>{
  return (
    <>
      <Head>
        <title>Frontend Mentor | Advice generator app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="UTF-8" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className='flex flex-col justify-center items-center h-screen w-screen bg-darkestGrey'>
        <div className='flex flex-col justify-center items-center h-3/4 w-full'>
          <Card/>        
        </div>
        <div className='flex flex-col justify-center items-center h-1/4 w-full'>
          <Footer/>
        </div>
      </div>

      

    </>
  );
};

export default Home;
