import Head from 'next/head'
import { NextPage } from 'next'
import Link from 'next/link';

const Home : NextPage =()=>{
  return (
    <>
      <Head>
        <title>Frontend Mentor | Advice generator app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className='text-black font-bold'>
        Hola mundo
      </div>
      <div className="">
        Challenge by <Link href="https://www.frontendmentor.io?ref=challenge" target="_blank"> Frontend Mentor</Link>. 
        Coded by <Link href="https://github.com/nestordqa"><span className='font-bold italic'> Néstor Quiñones</span></Link>.
      </div>
    </>
  );
};

export default Home;
